theme: jekyll-theme-hacker
title: Octo-Spork's new && very cool homepagedescription: >- #hello comment
  loving the schmiu, and the schnibb :*
baseurl: "Octo-Spork.github.io"
url:""#base hostoname&protocoll
